export const types = {
  FETCHING_DATA_REQUEST: 'FETCHING_DATA_REQUEST',

  FETCHING_DATA_SUCCESS: 'FETCHING_DATA_SUCCESS',

  FETCHING_DATA_ERROR: 'FETCHING_DATA_ERROR',

  ADD_PRODUCT_TO_CART: 'ADD_PRODUCT_TO_CART',

  INCREASE_PRODUCT_TO_CART: 'INCREASE_PRODUCT_TO_CART',

  DECREASE_PRODUCT_TO_CART: 'DECREASE_PRODUCT_TO_CART',

  DELETE_PRODUCT_TO_CART: 'DELETE_PRODUCT_TO_CART',

  REMOVE_PRODUCT_TO_CART: 'REMOVE_PRODUCT_TO_CART',
};
